### ISSUE TITLE
Error: Cannot find module './config'

### ISSUE THREAD

**Issue by ranjanpandey11111** [brentoneill/pokit-nodejs-demo#1]
on running node server.js it giving error "Error: Cannot find module './config'"

**Comment by brentoneill** [comment]
You are supposed to add the config yourself. Since these are config vars, they are not committed to the repo. See the `.gitignore`. Will update the `README.md` with the required vars.

**Comment by ranjanpandey11111** [comment]
it's working fine now, as I used credentials which i got after registering to above application. thank you for suggestion.

**Comment by brentoneill** [comment]
Great! Closing. Please reach out if you have any other issues.

**Comment by ranjanpandey11111** [comment]
Sure thanks
